/*
 * Ifra Inam
 * ICS4UE
 * Mr. Diakoloukas
 * 2023-08-04 
 * Purpose of Program: To simulate a grade book for a class of 30 students who each have four test scores 
 */

/**
 *
 * @author Ifra Inam
 */
public class U1A5b_IfraInam extends javax.swing.JFrame {

    /**
     * Creates new form U1A5b_IfraInam
     */
    public U1A5b_IfraInam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentGrades = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        txtTest1 = new javax.swing.JTextField();
        txtTest2 = new javax.swing.JTextField();
        txtTest4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JTextArea();
        lblTest1 = new javax.swing.JLabel();
        lblTest2 = new javax.swing.JLabel();
        lblTest3 = new javax.swing.JLabel();
        lblTest4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnStudentAverage = new javax.swing.JButton();
        btnCourseAverages = new javax.swing.JButton();
        txtOutput = new javax.swing.JTextField();
        txtTest3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grades");

        lblStudentGrades.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblStudentGrades.setForeground(new java.awt.Color(51, 0, 204));
        lblStudentGrades.setText("Student Grades");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFirstName.setText("First Name:");

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        txtTest1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTest2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTest4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtList.setColumns(20);
        txtList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtList.setRows(5);
        jScrollPane1.setViewportView(txtList);

        lblTest1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTest1.setText("Test 1:");

        lblTest2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTest2.setText("Test 2:");

        lblTest3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTest3.setText("Test 3:");

        lblTest4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTest4.setText("Test 4:");

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnStudentAverage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnStudentAverage.setText("Student Average");
        btnStudentAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAverageActionPerformed(evt);
            }
        });

        btnCourseAverages.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCourseAverages.setText("Course Averages");
        btnCourseAverages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAveragesActionPerformed(evt);
            }
        });

        txtOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTest3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFirstName)
                        .addGap(18, 18, 18)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTest1)
                                    .addComponent(lblTest2)
                                    .addComponent(lblTest3)
                                    .addComponent(lblTest4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTest1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(txtTest2)
                                    .addComponent(txtTest3)
                                    .addComponent(txtTest4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnExit))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(366, 366, 366)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnStudentAverage, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(btnCourseAverages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLastName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(lblStudentGrades)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblStudentGrades)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest1)
                    .addComponent(txtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnStudentAverage))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest2)
                    .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseAverages)
                    .addComponent(btnList))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTest3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest4)
                            .addComponent(txtTest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnExit)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // initializes the 2D student grade book array
    String studentGradeBook[][] = new String[30][6];
    
    // custom method to find a student's average in the course
    public double studentAvg(String firstName, String lastName) { // parameters of a student's first and last name are needed to acces their test marks
        double avg = 0;
        for (int i = 0; i < studentGradeBook.length; i++) {
            if (studentGradeBook[i][0].equals(firstName) && studentGradeBook[i][1].equals(lastName)) { // finds the student's first and last name in the array 
                // converts the user's string test marks into doubles
                double test1_doub = Double.parseDouble(studentGradeBook[i][2]); 
                double test2_doub = Double.parseDouble(studentGradeBook[i][3]);
                double test3_doub = Double.parseDouble(studentGradeBook[i][4]);
                double test4_doub = Double.parseDouble(studentGradeBook[i][5]);
                avg = (test1_doub + test2_doub + test3_doub + test4_doub) / 4; // finds the average of the student's tests 
                break;
            } 
            else if (i==studentGradeBook.length-1) {
                txtOutput.setText("Student does not exist.");
                return 0;
            }
        }
        return avg;
    } 
    
    private void btnCourseAveragesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAveragesActionPerformed
        // TODO add your handling code here:
        
        int studentcount = 0; // sets the number of students to 0 
        double total = 0;
        for (int i = 0; i < studentGradeBook.length; i++) {
            // finds the number of students by checking if information is stored in each array of the 2D array --> if information is present, student count increases
            if(studentGradeBook[i][0]!= null){ 
               studentcount++;
               total+=studentAvg(studentGradeBook[i][0], studentGradeBook[i][1]); // calls the studentAvg method to optain the averages of each student and adds all averages together 
            }
        }
        // divides the added averages by the number of students 
        double courseAvg = total/studentcount; 
        txtOutput.setText("The course average is " + Double.toString(courseAvg) + "%."); // outputs the course average onto the GUI
        
    }//GEN-LAST:event_btnCourseAveragesActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        // retrieves user input 
        String fName = txtFirstName.getText(); 
        String lName = txtLastName.getText(); 
        String test1 = txtTest1.getText();
        String test2 = txtTest2.getText();
        String test3 = txtTest3.getText();
        String test4 = txtTest4.getText();
        
        // checks if the user has not inputed all the required information and outputs an appropriate message to notify them
        if (fName.equals("") || lName.equals("") || test1.equals("") || test2.equals("") || test3.equals("") || test4.equals("")) {
            txtOutput.setText("You left a piece of information empty.");
            return;
        }
        
        for (int i = 0; i < studentGradeBook.length; i++) {
            // checks if a student has been added more than one time
            if (studentGradeBook[i][0]!=null && studentGradeBook[i][1]!=null && studentGradeBook[i][0].equals(fName) && studentGradeBook[i][1].equals(lName))  {
                txtOutput.setText("Student already exists.");
                break;
            } 
            else { 
                try { 
                    // converts the user's string test marks into doubles 
                    double test1_doub = Double.parseDouble(test1);
                    double test2_doub = Double.parseDouble(test2);
                    double test3_doub = Double.parseDouble(test3);
                    double test4_doub = Double.parseDouble(test4);
                    // adds user input into the student grade book array (only if information in an array of the 2D array is empty)
                    if (studentGradeBook[i][0] == null) {
                        txtOutput.setText("");
                        studentGradeBook[i][0] = fName;
                        studentGradeBook[i][1] = lName; 
                        studentGradeBook[i][2] = test1; 
                        studentGradeBook[i][3] = test2; 
                        studentGradeBook[i][4] = test3; 
                        studentGradeBook[i][5] = test4;
                        break;
                    }
                    // checks if array is full and outputs the appropriate message to notify user
                    else{
                        if(i==studentGradeBook.length-1) {
                            txtOutput.setText("The class is at capacity.");
                            break; 
                        }
                    }
                }    
                // used to check if the test marks are numbers 
                catch (NumberFormatException e) {
                    txtOutput.setText("You must enter a number for the grades.");
                }
            }
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        
        txtList.setText(""); // used to clear the text area every time the list button is pressed 
        // used to output the list onto the GUI
        for(int i = 0; i < studentGradeBook.length; i++) {
            for (int j = 0; j < studentGradeBook[i].length; j++) {
                if(studentGradeBook[i][j] == null) break; // only allows arrays of the 2D array that are not empty to be outputted 
                txtList.append(studentGradeBook[i][j] + ", ");
            }
            txtList.append("\n");
        }
    }//GEN-LAST:event_btnListActionPerformed

    private void btnStudentAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAverageActionPerformed
        // TODO add your handling code here:
        
        // retrieving user input
        String fName = txtFirstName.getText(); 
        String lName = txtLastName.getText(); 
        
        if (fName.equals("") || lName.equals("")) {
            txtOutput.setText("You left a piece of information empty.");
            return;
        }
        
        double studentAvg = (studentAvg(fName, lName)); // calls the studentAvg method and stores it into a varaible called studentAvg 
        txtOutput.setText(fName + " " + lName + "'s average is " + Double.toString(studentAvg) + "%."); // outputs the student's average
    
    }//GEN-LAST:event_btnStudentAverageActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here: 
        
        System.exit(0); // Exit the application. 
        
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A5b_IfraInam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A5b_IfraInam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A5b_IfraInam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A5b_IfraInam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A5b_IfraInam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCourseAverages;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnStudentAverage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblStudentGrades;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JLabel lblTest4;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtList;
    private javax.swing.JTextField txtOutput;
    private javax.swing.JTextField txtTest1;
    private javax.swing.JTextField txtTest2;
    private javax.swing.JTextField txtTest3;
    private javax.swing.JTextField txtTest4;
    // End of variables declaration//GEN-END:variables
}
